# Generated by Django 5.1.4 on 2025-01-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano_pub', models.IntegerField()),
                ('autor', models.CharField(max_length=100)),
                ('numero_paginas', models.IntegerField()),
            ],
        ),
    ]
